config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'

  resources :recipes
  resources :meal_plans
  resources :foods

  root 'meal_plans#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food.rb
class Food < ApplicationRecord
  has_one :recipe
  has_one :meal_plan
end

app/models/meal_plan.rb
class MealPlan < ApplicationRecord
  has_many :food
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :food
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: [:show, :edit, :update, :destroy]

  # GET /foods
  # GET /foods.json
  def index
    @foods = Food.all
  end

  # GET /foods/1
  # GET /foods/1.json
  def show
  end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit
  end

  # POST /foods
  # POST /foods.json
  def create
    @food = Food.new(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to @food, notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1
  # PATCH/PUT /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to @food, notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1
  # DELETE /foods/1.json
  def destroy
    @food.destroy
    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food
      @food = Food.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_params
      params.require(:food).permit(:rating, :david_rating, :longevity, :notes, :recipe_id, :meal_plan_id)
    end
end

app/controllers/meal_plans_controller.rb
class MealPlansController < ApplicationController
  before_action :set_meal_plan, only: [:show, :edit, :update, :destroy]

  # GET /meal_plans
  # GET /meal_plans.json
  def index
    @meal_plans = MealPlan.all
  end

  # GET /meal_plans/1
  # GET /meal_plans/1.json
  def show
  end

  # GET /meal_plans/new
  def new
    @meal_plan = MealPlan.new
  end

  # GET /meal_plans/1/edit
  def edit
  end

  # POST /meal_plans
  # POST /meal_plans.json
  def create
    @meal_plan = MealPlan.new(meal_plan_params)

    respond_to do |format|
      if @meal_plan.save
        format.html { redirect_to @meal_plan, notice: 'Meal plan was successfully created.' }
        format.json { render :show, status: :created, location: @meal_plan }
      else
        format.html { render :new }
        format.json { render json: @meal_plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meal_plans/1
  # PATCH/PUT /meal_plans/1.json
  def update
    respond_to do |format|
      if @meal_plan.update(meal_plan_params)
        format.html { redirect_to @meal_plan, notice: 'Meal plan was successfully updated.' }
        format.json { render :show, status: :ok, location: @meal_plan }
      else
        format.html { render :edit }
        format.json { render json: @meal_plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meal_plans/1
  # DELETE /meal_plans/1.json
  def destroy
    @meal_plan.destroy
    respond_to do |format|
      format.html { redirect_to meal_plans_url, notice: 'Meal plan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meal_plan
      @meal_plan = MealPlan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meal_plan_params
      params.require(:meal_plan).permit(:name, :week, :image, :filling, :longevity, :rating, :prep_time, :calories, :notes)
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:name, :image, :rating, :david_rating, :longevity, :recipe, :notes, :calories, :protein, :lipids, :carbs, :meal_plan_id)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meal_plans_helper.rb
module MealPlansHelper
end

app/helpers/recipe_helper.rb
module RecipeHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/foods/_form.html.erb
<%= form_for(food) do |f| %>
  <% if food.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
      <% food.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :meal_plan_id %>
    <%= f.collection_select(:meal_plan_id, MealPlan.all, :id, :name) %>
  </div>

  <div class="field">
    <%= f.label :recipe_id %>
    <%= f.collection_select(:recipe_id, Recipe.all, :id, :name) %>
  </div>

  <div class="field">
    <%= f.label :rating %>
    <%= f.number_field :rating %>
  </div>

  <div class="field">
    <%= f.label :david_rating %>
    <%= f.number_field :david_rating %>
  </div>

  <div class="field">
    <%= f.label :longevity %>
    <%= f.number_field :longevity %>
  </div>

  <div class="field">
    <%= f.label :notes %>
    <%= f.text_field :notes %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/foods/edit.html.erb
<h1>Editing Food</h1>

<%= render 'form', food: @food %>

<%= link_to 'Show', @food %> |
<%= link_to 'Back', foods_path %>

app/views/foods/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Foods</h1>

<table>
  <thead>
    <tr>
      <th>Rating</th>
      <th>David rating</th>
      <th>Longevity</th>
      <th>Notes</th>
      <th>Recipe</th>
      <th>Meal Plan</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @foods.each do |food| %>
      <tr>
        <td><%= food.rating %></td>
        <td><%= food.david_rating %></td>
        <td><%= food.longevity %></td>
        <td><%= food.notes %></td>
        <td><%= food.recipe_id %></td>
        <td><%= food.meal_plan_id %></td>
        <td><%= link_to 'Show', food %></td>
        <td><%= link_to 'Edit', edit_food_path(food) %></td>
        <td><%= link_to 'Destroy', food, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Food', new_food_path %>

app/views/foods/new.html.erb
<h1>New Food</h1>

<%= render 'form', food: @food %>

<%= link_to 'Back', foods_path %>

app/views/foods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rating:</strong>
  <%= @food.rating %>
</p>

<p>
  <strong>David rating:</strong>
  <%= @food.david_rating %>
</p>

<p>
  <strong>Longevity:</strong>
  <%= @food.longevity %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @food.notes %>
</p>

<p>
  <strong>Recipe:</strong>
  <%= @food.recipe_id %>
</p>

<p>
  <strong>Meal plan:</strong>
  <%= @food.meal_plan_id %>
</p>

<%= link_to 'Edit', edit_food_path(@food) %> |
<%= link_to 'Back', foods_path %>

app/views/items/_form.html.erb
<%= form_for(item) do |f| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.text_field :image %>
  </div>

  <div class="field">
    <%= f.label :rating %>
    <%= f.number_field :rating %>
  </div>

  <div class="field">
    <%= f.label :david_rating %>
    <%= f.number_field :david_rating %>
  </div>

  <div class="field">
    <%= f.label :longevity %>
    <%= f.number_field :longevity %>
  </div>

  <div class="field">
    <%= f.label :recipe %>
    <%= f.text_field :recipe %>
  </div>

  <div class="field">
    <%= f.label :notes %>
    <%= f.text_area :notes %>
  </div>

  <div class="field">
    <%= f.label :calories %>
    <%= f.number_field :calories %>
  </div>

  <div class="field">
    <%= f.label :protein %>
    <%= f.number_field :protein %>
  </div>

  <div class="field">
    <%= f.label :lipids %>
    <%= f.number_field :lipids %>
  </div>

  <div class="field">
    <%= f.label :carbs %>
    <%= f.number_field :carbs %>
  </div>

  <div class="field">
    <%= f.label :meal_plan_id %>
    <%= f.text_field :meal_plan_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>First1200</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/meal_plans/_form.html.erb
<%= form_for(meal_plan) do |f| %>
  <% if meal_plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(meal_plan.errors.count, "error") %> prohibited this meal_plan from being saved:</h2>

      <ul>
      <% meal_plan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :week %>
    <%= f.date_select :week %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.text_field :image %>
  </div>

  <div class="field">
    <%= f.label :filling %>
    <%= f.number_field :filling %>
  </div>

  <div class="field">
    <%= f.label :longevity %>
    <%= f.number_field :longevity %>
  </div>

  <div class="field">
    <%= f.label :rating %>
    <%= f.number_field :rating %>
  </div>

  <div class="field">
    <%= f.label :prep_time %>
    <%= f.number_field :prep_time %>
  </div>

  <div class="field">
    <%= f.label :calories %>
    <%= f.number_field :calories %>
  </div>

  <div class="field">
    <%= f.label :notes %>
    <%= f.text_area :notes %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/meal_plans/edit.html.erb
<h1>Editing Meal Plan</h1>

<%= render 'form', meal_plan: @meal_plan %>

<%= link_to 'Show', @meal_plan %> |
<%= link_to 'Back', meal_plans_path %>

app/views/meal_plans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Meal Plans</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Week</th>
      <th>Image</th>
      <th>Filling</th>
      <th>Longevity</th>
      <th>Rating</th>
      <th>Prep time</th>
      <th>Calories</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @meal_plans.each do |meal_plan| %>
      <tr>
        <td><%= meal_plan.name %></td>
        <td><%= meal_plan.week %></td>
        <td><%= meal_plan.image %></td>
        <td><%= meal_plan.filling %></td>
        <td><%= meal_plan.longevity %></td>
        <td><%= meal_plan.rating %></td>
        <td><%= meal_plan.prep_time %></td>
        <td><%= meal_plan.calories %></td>
        <td><%= meal_plan.notes %></td>
        <td><%= link_to 'Show', meal_plan %></td>
        <td><%= link_to 'Edit', edit_meal_plan_path(meal_plan) %></td>
        <td><%= link_to 'Destroy', meal_plan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Meal Plan', new_meal_plan_path %>

app/views/meal_plans/new.html.erb
<h1>New Meal Plan</h1>

<%= render 'form', meal_plan: @meal_plan %>

<%= link_to 'Back', meal_plans_path %>

app/views/meal_plans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @meal_plan.name %>
</p>

<p>
  <strong>Week:</strong>
  <%= @meal_plan.week %>
</p>

<p>
  <strong>Image:</strong>
  <%= @meal_plan.image %>
</p>

<p>
  <strong>Filling:</strong>
  <%= @meal_plan.filling %>
</p>

<p>
  <strong>Longevity:</strong>
  <%= @meal_plan.longevity %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @meal_plan.rating %>
</p>

<p>
  <strong>Prep time:</strong>
  <%= @meal_plan.prep_time %>
</p>

<p>
  <strong>Calories:</strong>
  <%= @meal_plan.calories %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @meal_plan.notes %>
</p>

<%= link_to 'Edit', edit_meal_plan_path(@meal_plan) %> |
<%= link_to 'Back', meal_plans_path %>

app/views/recipes/_form.html.erb
<%= form_for(recipe) do |f| %>
  <% if recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :recipe_url %>
    <%= f.text_field :recipe_url %>
  </div>

  <div class="field">
    <%= f.label :nutrition_url %>
    <%= f.text_field :nutrition_url %>
  </div>

  <div class="field">
    <%= f.label :notes %>
    <%= f.text_area :notes %>
  </div>

  <div class="field">
    <%= f.label :calories %>
    <%= f.number_field :calories %>
  </div>

  <div class="field">
    <%= f.label :protein %>
    <%= f.number_field :protein %>
  </div>

  <div class="field">
    <%= f.label :lipids %>
    <%= f.number_field :lipids %>
  </div>

  <div class="field">
    <%= f.label :carbs %>
    <%= f.number_field :carbs %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Recipes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Recipe URL</th>
      <th>Nutrition URL</th>
      <th>Notes</th>
      <th>Calories</th>
      <th>Protein</th>
      <th>Lipids</th>
      <th>Carbs</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <td><%= recipe.name %></td>
        <td><%= recipe.recipe_url %></td>
        <td><%= recipe.nutrition_url %></td>
        <td><%= recipe.notes %></td>
        <td><%= recipe.calories %></td>
        <td><%= recipe.protein %></td>
        <td><%= recipe.lipids %></td>
        <td><%= recipe.carbs %></td>
        <td><%= link_to 'Show', recipe %></td>
        <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
        <td><%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recipe', new_recipe_path %>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @recipe.name %>
</p>

<p>
  <strong>Nutrition:</strong>
  <%= @recipe.nutrition_url %>
</p>

<p>
  <strong>Recipe:</strong>
  <%= @recipe.recipe_url %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @recipe.notes %>
</p>

<p>
  <strong>Calories:</strong>
  <%= @recipe.calories %>
</p>

<p>
  <strong>Protein:</strong>
  <%= @recipe.protein %>
</p>

<p>
  <strong>Lipids:</strong>
  <%= @recipe.lipids %>
</p>

<p>
  <strong>Carbs:</strong>
  <%= @recipe.carbs %>
</p>

<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>

app/views/static_pages/home.html.erb
<h1>First 1200</h1>
<p>This is the home page for my meal plan tracking site.</p>